name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  IMAGE_TAG: $(date +%s)

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build app-dotnet --tag webapp:$IMAGE_TAG
    - name: Tag the Docker image
      run: docker tag webapp:$IMAGE_TAG manubop/webapp:$IMAGE_TAG
